### PR TITLE
GetRtpReceiver and GetRtpSender returned a wrong type may cause crash.

### PR DESCRIPTION
**Pull request by PeterCang**
in src\Handler.cpp
recvResult.rtpReceiver = transceiver->receiver();

**transceiver->receiver();** returns **rtc::scoped_refptr<RtpReceiverInterface>**
but **struct RecvResult** holds RtpReceiverInterface*

so if the result returned from **transceiver->receiver()** has been deleted in **pc\rtp_transceiver.cc**, and you are using a return from **Consumer::GetRtpReceiver()**, it may crash.

the same in:
**sendResult.rtpSender     = transceiver->sender();
Producer::GetRtpSender().**

### CODE REVIEW

**Comment by PeterCang** [comment]
upgrade codes to build on webrtc m92

**Comment by PeterCang** [comment]
on webrtc m92, CodecParameterMap has been moved to namspace cricket, and GenerateProfileLevelIdForAnswer renamed to H264GenerateProfileLevelIdForAnswer.

**Comment by jmillan** [comment]
@PeterCang,

Is this basically a PR to move to m92?

**Comment by PeterCang** [comment]
> @PeterCang,
> 
> Is this basically a PR to move to m92?

This problem also existed in the old version.

**Comment by jmillan** [comment]
Then this PR contains a bugfix and and the required changes to move to m92, right? This won't work on current m84, correct?

**Comment by PeterCang** [comment]
> Then this PR contains a bugfix and and the required changes to move to m92, right? This won't work on current m84, correct?

yeah.

**Comment by jmillan** [comment]
After compiling libwebrtc `branch-heads/4515` I get some warnings and errors when builing libmediasoupclient:

Screenshot 2021-08-23 at 12 21 01

**Comment by PeterCang** [comment]
> After compiling libwebrtc `branch-heads/4515` I get some warnings and errors when builing libmediasoupclient:
> 
> Screenshot 2021-08-23 at 12 21 01

Ah, I never build the libmediasoupclient test module.

yes,  rtc::CriticalSection has been removed and replaced by webrtc::Mutex in the new version of WebRTC.

**Comment by PeterCang** [comment]
So should I fix the errors and warnings and make a new PR?

**Comment by jmillan** [comment]
This PR contains several different changes.

BTW, we already use m94 in v3.
Also, the 'maxaveragebitrate' support for Opus has been merged separately.

If needed please make the corresponding PR with a specific change  each.

**Pull request closed without merging**
