### PR TITLE
fix order of encodings

### LINKED ISSUE #90: Order of rtp encoding is different from sdp
In `Utils::getRtpEncodings(const json& offerMediaObject)`, we use a map to save rtp ssrcs and rtx ssrcs, and finally put them into an array.
This will re-sort the ssrcs by ascending order, and maybe different from the orginal order in sdp.
And we also do not care about the order in ssrc-group:SIM or ssrc-group:SIMULCAST.

```
			std::map<uint32_t, uint32_t> ssrcToRtxSsrc;

			auto jsonSsrcGroupsIt = offerMediaObject.find("ssrcGroups");
			if (jsonSsrcGroupsIt != offerMediaObject.end())
			{
				auto ssrcGroups = (*jsonSsrcGroupsIt);

				// First assume RTX is used.
				for (auto& line : ssrcGroups)
				{
					if (line["semantics"].get<std::string>() != "FID")
						continue;

					auto fidLine = line["ssrcs"].get<std::string>();
					auto v       = mediasoupclient::Utils::split(fidLine, ' ');

					auto ssrc    = std::stoull(v[0]);
					auto rtxSsrc = std::stoull(v[1]);

					if (ssrcs.find(ssrc) != ssrcs.end())
					{
						// Remove both the SSRC and RTX SSRC from the Set so later we know that they
						// are already handled.
						ssrcs.erase(ssrc);
						ssrcs.erase(rtxSsrc);
					}

					// Add to the map.
					ssrcToRtxSsrc[ssrc] = rtxSsrc;
				}
			}

			// If the Set of SSRCs is not empty it means that RTX is not being used, so take
			// media SSRCs from there.
			for (auto& ssrc : ssrcs)
			{
				// Add to the map.
				ssrcToRtxSsrc[ssrc] = 0u;
			}

			// Fill RTP parameters.

			auto encodings = json::array();

			for (auto& kv : ssrcToRtxSsrc)
			{
				json encoding = { { "ssrc", kv.first } };

				if (kv.second != 0u)
					encoding["rtx"] = { { "ssrc", kv.second } };

				encodings.push_back(encoding);
			}

			return encodings;
```

### PR DESCRIPTION
**Pull request by penguinol**
fix #90

### CODE REVIEW

**Comment by ibc** [comment]
Great. Confirmed that this change fixes #90?

**Comment by penguinol** [comment]
Sorry, still need to edit. it seems unordered_map/set can not ensure sort in insert order

**Comment by ibc** [comment]
> it seems unordered_map/set can not ensure sort in insert order

yep, that was my feeling.

**Comment by penguinol** [comment]
done

**Comment by jmillan** [comment]
Great, thanks @penguinol!

**Pull request merged**
