### PR TITLE
Extract error message data

### PR DESCRIPTION
**Pull request by adriancretu**
Fix compiling against WebRTC m113.

### CODE REVIEW

**Review by jmillan — APPROVED** [review]

**Comment by jmillan** [comment]
Is m112 working with this fix?

**Comment by adriancretu** [comment]
No, this fix addresses a change found in WebRTC m113. It will not compile with m112 (hence the PR branch name `m113`).

**Comment by jmillan** [comment]
I don't know how I could accept this PR that breaks the target branch.., reversing.

**Comment by adriancretu** [comment]
Yeah, this is what I've also hinted - even the branch name of the PR was named `m113` to hint it rather belongs to a new `m113` origin branch. Sorry for the confusion.

**Pull request merged**
