### PR TITLE
fix android build error

### PR DESCRIPTION
**Pull request by chenjim**

### CODE REVIEW

**Comment by ibc** [comment]
Which issue in Android does this PR fix? Can you explain it?

**Comment by chenjim** [comment]
add `whole-archive`  to keep symbols，otherwise crash  
``` 
org.mediasoup.droid.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mediasoup.droid.demo, PID: 6452
    java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
        at org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals(Native Method)
        at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:306)
        at org.mediasoup.droid.MediasoupClient.initialize(MediasoupClient.java:25)
        at org.mediasoup.droid.MediasoupClient.initialize(MediasoupClient.java:15)
        at org.mediasoup.droid.demo.Application.onCreate(Application.java:19)
```

reference 
<https://github.com/haiyangwu/mediasoup-client-android/blob/dev/mediasoup-client/deps/libmediasoupclient/CMakeLists.txt>

**Comment by ibc** [comment]
@jmillan any concerns about this?

**Comment by jmillan** [comment]
Since you are using mediasoup-client-android, maybe you can create an issue in that project?

**Comment by chenjim** [comment]
ok

**Pull request closed without merging**
